# Generated by Django 4.0.3 on 2022-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sprint',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
