# Generated by Django 4.0.3 on 2022-03-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users_rename_issue_id_issue_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
