# Generated by Django 4.0.3 on 2022-03-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_issue_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issue')),
                ('user_rel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.users')),
            ],
        ),
    ]
