# Generated by Django 4.0.3 on 2022-03-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_issue_date_created_alter_project_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(blank=True, default=None, max_length=1500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.labels'),
        ),
    ]
