# Generated by Django 4.0.3 on 2022-03-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_labels_alter_issue_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='Label',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
