# Generated by Django 4.0.3 on 2022-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_labels_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
