# Generated by Django 4.0.3 on 2022-03-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_issue_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='Label',
            new_name='label',
        ),
    ]
