# Generated by Django 4.0.3 on 2022-03-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_label_labels_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='label',
        ),
    ]
