# Generated by Django 4.0.3 on 2022-03-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_issue_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labels',
        ),
    ]
